apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-tt15551dotcc-default
  namespace: default
spec:
  dnsNames:
  - tt15551.cc
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-http01-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: cert-tt15551dotcc-default
  usages:
  - server auth
  - client auth
