apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-key
data:
  nginx.key: |-
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIH1/xZewVoF1y896Vw0AbzBvhcEzFfr7MnHwAe3HJOBGoAoGCCqGSM49
    AwEHoUQDQgAEwX5PBfI6lLqgiwVHSttoYevKrxxWPosfCP361gWnIqwDP2bVwRJX
    Su6vdj3z2stwerEAFQ8JZvAWnupyaaq2Cg==
    -----END EC PRIVATE KEY-----
