apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-crt
data:
  nginx.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDazCCAlOgAwIBAgIUK7De9E8GRvHFhjXUQGW2O4AD+CowDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMjA3MzAxMDU5MDNaFw0yMzA3
    MzAxMDU5MDNaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
    HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQC+FdbRKXENaAzLMG5ELkgJwUJfRi2l8ck7GgryN0YJ
    k9cdfZtTg/XQReHWkNC6sFIFaezS3c/Ojwd8yYHnt3lpqx8MdmTFetYRJpdfbB30
    uGsZAHlcADreJpbdkAu/2BYWbHwev9e2ULciFadVoG+Ep0a9fYJFz4N+KPW0qVgV
    XXiOcsZmA3H9xi6xheyHkYTXv8gs9iwoI6n/8/HStka8v6pZS6dpB34ztYnv8z8j
    4T+5OPVhZv1KZp6rlnuEpRhz8SBMmli20EXPMnpkbgMTGN1BWqZr+tATQ2Q55/0W
    v+4lDua1yTa8Wn8TQtw5z8rEdmIq9PSOZi+mDFX5q0I7AgMBAAGjUzBRMB0GA1Ud
    DgQWBBS6Wr/tdK3vhLnq/7eXnqnsIclUVDAfBgNVHSMEGDAWgBS6Wr/tdK3vhLnq
    /7eXnqnsIclUVDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCy
    AHWOfzbDc8the06BbV60QbZIkfS86ez1HFeDUZEeFfCQ9zyzHlrDA3Ah5tJ+Eoxx
    Ym2lfqYCv/hcXpFbRKjq3cY4fIIblxQuQd1Z+vlwZf3cd8XCcRQFBJv4KXj1gixD
    1bWaU9rGzXWims2BAMEfsKsXxTauuDhe5HNSveh4rJdGuTmYLgg4Ru/sNSp5mqRc
    /caU5N0DL16hL3wAce7nq9kjXvXX8o6M79a3Pr6mV6pjnRNtnN2SL3Y+RryKjJs7
    pS9lsNihSdQZjQqCnEeCaeqg98NxYr24u0F0Wn6kmidfWhujBZjy14Guo6jnGS/p
    mlaFzEl31iEDe/DmdcVb
    -----END CERTIFICATE-----
