apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:5M max_size=1g inactive=10m use_temp_path=on;
      server {
        server_name myserver;
        listen 443 ssl http2;
        #ssl_certificate nginx.crt;
        #ssl_certificate_key nginx.key;

        proxy_cache my_cache;
        #proxy_cache_revalidate on;
        proxy_cache_use_stale updating error timeout http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;
        proxy_cache_lock on;
        proxy_cache_valid any 30s;
        proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $proxy_host;
        location ^~ / {
          proxy_pass http://first.tt5.workers.dev;
        }
        location ^~ /services/nav {
          rewrite ^/services/nav / break;
          proxy_pass http://nav.tt5.workers.dev;
        }
      }
    }
  nginx.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+FdbRKXENaAzL
    MG5ELkgJwUJfRi2l8ck7GgryN0YJk9cdfZtTg/XQReHWkNC6sFIFaezS3c/Ojwd8
    yYHnt3lpqx8MdmTFetYRJpdfbB30uGsZAHlcADreJpbdkAu/2BYWbHwev9e2ULci
    FadVoG+Ep0a9fYJFz4N+KPW0qVgVXXiOcsZmA3H9xi6xheyHkYTXv8gs9iwoI6n/
    8/HStka8v6pZS6dpB34ztYnv8z8j4T+5OPVhZv1KZp6rlnuEpRhz8SBMmli20EXP
    MnpkbgMTGN1BWqZr+tATQ2Q55/0Wv+4lDua1yTa8Wn8TQtw5z8rEdmIq9PSOZi+m
    DFX5q0I7AgMBAAECggEBAIn2M9nPaDxAvrhiyEU4ChT6bX/U4aDFojYBKtyt/WlK
    IiFHXwr4hdrKPaWLqdM10fIX9Uj+sKrM6LRLVLunULm+92QGMhGam/AKwGcDg6Jw
    j1qwG2UIzbEa9PiOaditrypLRrLSrm+mmaRlbvQY45e2CQPTKlAc0uUoOV0MY9/s
    nS7Gv4tdyDJioPnWJolvECxtx3GPtXQhm7R7WgnMLFKa+qLkoRbUIyb08W9pvd+t
    wkCtxnunnOiOmTSef1TKxZpc4cliQbBx+0pZPET3+h40ANibcwNcv1dg4ftyP+vG
    /iYkz2miYFjZkC86TZSDLcCPO2WYGuiAsvXSGvT7uXECgYEA3rAHd00aCiE/izUb
    LV7nPhVlzlGPzhxQBKDepriM51q4yXqpPEM9nzi3JP435ORJyyRSPccfJbClB6+t
    Z16h83AZhbDouujRswnPZXwjvmOhoxQ6I9M1BbA8ruiVM7UU9k9WlsHn1zbxI3h9
    gDI0CdFRfBgreAOwryhf7WQ9IscCgYEA2oVIbpITKV1jU01yl3anBFveJdIatmtf
    e1vsc7VjU0Tsv1yvStkI4i6mTLkuqQW8tb6XC/EMdEfFANSfnV8loVrCQhVsbjPY
    V08ZRQg2+/D/Cqkl6mv+5oiy74GLeSWGRiiFrk6ygb540fNNWO+iBxbgEvGrP2ut
    s28gJkhNcO0CgYEAsamC611qDvbjuW5PFm2G0/NCW86ainfwJyEpQZ4vXEz27Fee
    OWPz/9nB1BO2CDlR3m5F5t+8K9e4cl9oWvYXAx9GXXD83FHvK4YCHxdhdP4L8Q2s
    LPTOcpFeeLU6hBxOcwxtKq3dB8jfrcrtZZ+oAMUs23J1C7T1+2icz8qPM/UCgYAJ
    oEtzi33KmbGRbtz4bSKoX3+mvN2uYYaAQall43yvo16mg2e5bVwl0pZC1PmIOpd4
    jh/LR+AbkznLcpJhdVqMBBqAnL79D82c8wAS+WyqppAloRPpgr5k22q+gD9ro8qJ
    dqmE5zSX4JMj9IrYux2xIEHYs8qubYjmWaPZ6991dQKBgBiuhRaEN0vLImBGxRAf
    DT4YTokEdLpI8VJog+xD0DiEmCPPnFdJUAoAhfFrDKH21VOfVjbCEPVebYOyIOGs
    xvk+Zw4lWTWdgGYmpVfC9YyH7zklWKuTJjhJ3e3Y1cbz0UtRhy+Sxq0nzGSY7RPl
    VS/CXlV0wBk4iI8bpbFiMFd6
    -----END PRIVATE KEY-----
  nginx.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDazCCAlOgAwIBAgIUK7De9E8GRvHFhjXUQGW2O4AD+CowDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMjA3MzAxMDU5MDNaFw0yMzA3
    MzAxMDU5MDNaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
    HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQC+FdbRKXENaAzLMG5ELkgJwUJfRi2l8ck7GgryN0YJ
    k9cdfZtTg/XQReHWkNC6sFIFaezS3c/Ojwd8yYHnt3lpqx8MdmTFetYRJpdfbB30
    uGsZAHlcADreJpbdkAu/2BYWbHwev9e2ULciFadVoG+Ep0a9fYJFz4N+KPW0qVgV
    XXiOcsZmA3H9xi6xheyHkYTXv8gs9iwoI6n/8/HStka8v6pZS6dpB34ztYnv8z8j
    4T+5OPVhZv1KZp6rlnuEpRhz8SBMmli20EXPMnpkbgMTGN1BWqZr+tATQ2Q55/0W
    v+4lDua1yTa8Wn8TQtw5z8rEdmIq9PSOZi+mDFX5q0I7AgMBAAGjUzBRMB0GA1Ud
    DgQWBBS6Wr/tdK3vhLnq/7eXnqnsIclUVDAfBgNVHSMEGDAWgBS6Wr/tdK3vhLnq
    /7eXnqnsIclUVDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCy
    AHWOfzbDc8the06BbV60QbZIkfS86ez1HFeDUZEeFfCQ9zyzHlrDA3Ah5tJ+Eoxx
    Ym2lfqYCv/hcXpFbRKjq3cY4fIIblxQuQd1Z+vlwZf3cd8XCcRQFBJv4KXj1gixD
    1bWaU9rGzXWims2BAMEfsKsXxTauuDhe5HNSveh4rJdGuTmYLgg4Ru/sNSp5mqRc
    /caU5N0DL16hL3wAce7nq9kjXvXX8o6M79a3Pr6mV6pjnRNtnN2SL3Y+RryKjJs7
    pS9lsNihSdQZjQqCnEeCaeqg98NxYr24u0F0Wn6kmidfWhujBZjy14Guo6jnGS/p
    mlaFzEl31iEDe/DmdcVb
    -----END CERTIFICATE-----


