apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-key
data:
  nginx.key: |-
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIFlyAIc2xP5Pd0pOMMbqPQDkAuUMVb0fQ8pUZLY1sEHjoAoGCCqGSM49
    AwEHoUQDQgAES1TocFohe2NWy2m57ET7sZi0vBL5i3M1H0UGGtugS3sZGOVVcEKO
    UJTwQ7gMiugFCr6jo9zDW3GjvfA5E7+2mw==
    -----END EC PRIVATE KEY-----
