apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-key
data:
  nginx.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+FdbRKXENaAzL
    MG5ELkgJwUJfRi2l8ck7GgryN0YJk9cdfZtTg/XQReHWkNC6sFIFaezS3c/Ojwd8
    yYHnt3lpqx8MdmTFetYRJpdfbB30uGsZAHlcADreJpbdkAu/2BYWbHwev9e2ULci
    FadVoG+Ep0a9fYJFz4N+KPW0qVgVXXiOcsZmA3H9xi6xheyHkYTXv8gs9iwoI6n/
    8/HStka8v6pZS6dpB34ztYnv8z8j4T+5OPVhZv1KZp6rlnuEpRhz8SBMmli20EXP
    MnpkbgMTGN1BWqZr+tATQ2Q55/0Wv+4lDua1yTa8Wn8TQtw5z8rEdmIq9PSOZi+m
    DFX5q0I7AgMBAAECggEBAIn2M9nPaDxAvrhiyEU4ChT6bX/U4aDFojYBKtyt/WlK
    IiFHXwr4hdrKPaWLqdM10fIX9Uj+sKrM6LRLVLunULm+92QGMhGam/AKwGcDg6Jw
    j1qwG2UIzbEa9PiOaditrypLRrLSrm+mmaRlbvQY45e2CQPTKlAc0uUoOV0MY9/s
    nS7Gv4tdyDJioPnWJolvECxtx3GPtXQhm7R7WgnMLFKa+qLkoRbUIyb08W9pvd+t
    wkCtxnunnOiOmTSef1TKxZpc4cliQbBx+0pZPET3+h40ANibcwNcv1dg4ftyP+vG
    /iYkz2miYFjZkC86TZSDLcCPO2WYGuiAsvXSGvT7uXECgYEA3rAHd00aCiE/izUb
    LV7nPhVlzlGPzhxQBKDepriM51q4yXqpPEM9nzi3JP435ORJyyRSPccfJbClB6+t
    Z16h83AZhbDouujRswnPZXwjvmOhoxQ6I9M1BbA8ruiVM7UU9k9WlsHn1zbxI3h9
    gDI0CdFRfBgreAOwryhf7WQ9IscCgYEA2oVIbpITKV1jU01yl3anBFveJdIatmtf
    e1vsc7VjU0Tsv1yvStkI4i6mTLkuqQW8tb6XC/EMdEfFANSfnV8loVrCQhVsbjPY
    V08ZRQg2+/D/Cqkl6mv+5oiy74GLeSWGRiiFrk6ygb540fNNWO+iBxbgEvGrP2ut
    s28gJkhNcO0CgYEAsamC611qDvbjuW5PFm2G0/NCW86ainfwJyEpQZ4vXEz27Fee
    OWPz/9nB1BO2CDlR3m5F5t+8K9e4cl9oWvYXAx9GXXD83FHvK4YCHxdhdP4L8Q2s
    LPTOcpFeeLU6hBxOcwxtKq3dB8jfrcrtZZ+oAMUs23J1C7T1+2icz8qPM/UCgYAJ
    oEtzi33KmbGRbtz4bSKoX3+mvN2uYYaAQall43yvo16mg2e5bVwl0pZC1PmIOpd4
    jh/LR+AbkznLcpJhdVqMBBqAnL79D82c8wAS+WyqppAloRPpgr5k22q+gD9ro8qJ
    dqmE5zSX4JMj9IrYux2xIEHYs8qubYjmWaPZ6991dQKBgBiuhRaEN0vLImBGxRAf
    DT4YTokEdLpI8VJog+xD0DiEmCPPnFdJUAoAhfFrDKH21VOfVjbCEPVebYOyIOGs
    xvk+Zw4lWTWdgGYmpVfC9YyH7zklWKuTJjhJ3e3Y1cbz0UtRhy+Sxq0nzGSY7RPl
    VS/CXlV0wBk4iI8bpbFiMFd6
    -----END PRIVATE KEY-----
