apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:1M max_size=1g inactive=1m use_temp_path=off;
      server {
        listen 80;
        server_name first.tt5.workers.dev;
        proxy_cache my_cache;
        #proxy_cache_revalidate on;
        proxy_cache_background_update on;
        proxy_cache_lock on;
        proxy_cache_valid any 1m;
        proxy_ignore_headers Cache-Control;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $proxy_host;
        location / {
            proxy_pass http://first.tt5.workers.dev;
        }
        location /services/nav {
            proxy_pass http://nav.tt5.workers.dev;
        }
      }
    }
