apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        counter: "14"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - name: https
            containerPort: 443
          - name: http
            containerPort: 80
          volumeMounts:
            - name: shared
              mountPath: /usr/share/nginx/html/
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-key
              mountPath: /etc/nginx/nginx.key
              subPath: nginx.key
              readOnly: true
            - name: nginx-crt
              mountPath: /etc/nginx/nginx.crt
              subPath: nginx.crt
              readOnly: true
      initContainers:
        - name: get-first
          image: busybox
          command:
            - wget
            - "-O"
            - "/shared/index.html"
            - https://first.tt5.workers.dev/
          volumeMounts:
            - name: shared
              mountPath: /shared
        - name: get-chessfont
          image: busybox
          command:
            - wget
            - "-O"
            - "/shared/alpha2.ttf"
            - " https://raw.githubusercontent.com/mcroitor/chess-fonts/main/ttf/alpha2.ttf"
          volumeMounts:
            - name: shared
              mountPath: /shared
        - name: get-alpinejs
          image: busybox
          command:
            - wget
            - "-O"
            - "/shared/alpine.js"
            - "https://unpkg.com/alpinejs@3.10.3/dist/cdn.min.js"
          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-key
          configMap:
            name: nginx-key
            items:
              - key: nginx.key
                path: nginx.key
        - name: nginx-crt
          configMap:
            name: nginx-crt
            items:
              - key: nginx.crt
                path: nginx.crt
