apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        counter: "2"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: shared
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      initContainers:
        - name: install
          image: busybox
          command:
            - wget
            - "-O"
            - "/shared/index.html"
            - https://first.tt5.workers.dev/
          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
