apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ext-access
spec:
  hosts:
  - "tt15551.cc"
  gateways:
  - my-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: nginx
        port:
          number: 80
  tls:
  - match:
    - port: 443
      sniHosts:
      - tt15551.cc
    route:
    - destination:
        host: nginx
        port:
          number: 443
