apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ext-access
spec:
  hosts:
  - "hello123.tk"
  gateways:
  - my-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - hello123.tk
    route:
    - destination:
        host: nginx
        port:
          number: 443
